# Generated by Django 6.0.2 on 2026-04-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Requirements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("req_id", models.CharField(max_length=50)),
                ("req_text", models.CharField(max_length=200)),
            ],
        ),
    ]
