# Generated by Django 6.0.2 on 2026-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirements",
            name="req_status",
            field=models.CharField(default="active", max_length=200),
        ),
        migrations.AlterField(
            model_name="requirements",
            name="req_id",
            field=models.CharField(default="0000", max_length=50),
        ),
        migrations.AlterField(
            model_name="requirements",
            name="req_text",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
