[pytest]
DJANGO_SETTINGS_MODULE = app.settings
# Optional: defines naming conventions for test discovery
python_files = tests.py test_*.py *_tests.py
# Optional: adds command line arguments by default
addopts = --reuse-db
